application: weathergirlbot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /
  static_files: index.html
  upload: index\.html

- url: /static
  static_dir: static

- url: /set_webhook
  login: admin
  script: main.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: ssl
  version: latest
